spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: 'jdbc:mysql://localhost:3306/uplus?useUnicode'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: dbsQUD15!!